services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        depends_on:
            - db
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        ports:
            - "8085:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: profilemuhammadiyah
            MYSQL_ROOT_PASSWORD: secret
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: profilemuhammadiyah-phpmyadmin
        restart: always
        ports:
            - 8086:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        depends_on:
            - db
        networks:
            - laravel

volumes:
    dbdata:

networks:
    laravel:
        driver: bridge
